### ISSUE TITLE
f5-cccl's dependencies are not installed when installing via pip

### ISSUE THREAD

**Issue by intgr** [f5devcentral/f5-cccl#243]
Hello. Using Python 3.7 on macOS, when I try to install `f5-cccl` using `pip`, it only installs the module, but not any of the dependencies required by f5-cccl. This appears to be an issue with cccl's packaging.

```
% mkdir -p /tmp/cccl-test
% cd /tmp/cccl-test
% python3 -m venv venv
% . ./venv/bin/activate

(venv) % pip install 'git+https://github.com/f5devcentral/f5-cccl#egg=f5_cccl'
Collecting f5_cccl from git+https://github.com/f5devcentral/f5-cccl#egg=f5_cccl
  Cloning https://github.com/f5devcentral/f5-cccl to /private/var/folders/38/kgvqw_b979g6b_2zpk009xc4d29zfz/T/pip-install-mwc5lm3w/f5-cccl
  Running command git clone -q https://github.com/f5devcentral/f5-cccl /private/var/folders/38/kgvqw_b979g6b_2zpk009xc4d29zfz/T/pip-install-mwc5lm3w/f5-cccl
Installing collected packages: f5-cccl
  Running setup.py install for f5-cccl ... done
Successfully installed f5-cccl-0.1.0

(venv) % python -c 'from f5_cccl.api import F5CloudServiceManager'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/private/tmp/cccl-test/venv/lib/python3.7/site-packages/f5_cccl/api.py", line 22, in <module>
    from f5_cccl.bigip import BigIPProxy
  File "/private/tmp/cccl-test/venv/lib/python3.7/site-packages/f5_cccl/bigip.py", line 22, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

(venv) % pip freeze -l
f5-cccl==0.1.0
```

The same also happens when I run `pip install -e .` from a git checkout of f5-cccl repository.

**Comment by ssurenr** [comment]
Use Python 2.7

**Comment by ssurenr** [comment]
Please reopen if the issue still persists.

**Comment by intgr** [comment]
Sorry for not replying in a timely manner.

It seems that f5-cccl works just fine with Python 3.7. I really don't want to downgrade to Python 2 and it will be out of support soon, so that's not a satisfactory solution.

I can give a shot at debugging this issue myself.
